### ISSUE TITLE
Update CRDs to apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by wallrj** [cert-manager/sample-external-issuer#6]
Currently:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
```

So it might just require a newer version of controller-tools which is currently at 0.5.0.
v1 CRDs were introduced in 0.4.0:
 * https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.4.0
